use master
GO
drop database  if exists movieApp
create database movieApp
use movieApp

create table userApp (
	username varchar (20) primary key,
	email varchar (30),
	passwordUser varchar (20),
	constraint ck_email check (email like '%@%.%')
)

create table movieApp (
	idMovie int primary key identity (1, 1),
	movieName varchar (50),
	movieDirector varchar (20),
	movieDescription varchar (1500),
	movieBuyPrice money,
	movieRentPrice money
)


insert userApp (username, email, passwordUser) values ('admin', 'admin@admin.admin', 'admin')

insert movieApp (movieName, movieDirector, movieDescription, movieBuyPrice, movieRentPrice) 
values ('Spider-Man: No Way Home', 'Jon Watts', 'Spider-Man: No Way Home is a 2021 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and Spider-Man: Far From Home (2019), and is the 27th film in the Marvel Cinematic Universe (MCU). The film is directed by Jon Watts and written by Chris McKenna and Erik Sommers, and stars Tom Holland as Peter Parker / Spider-Man alongside Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori, Marisa Tomei, Andrew Garfield, and Tobey Maguire. In the film, Parker asks Dr. Stephen Strange (Cumberbatch) to make his identity as Spider-Man a secret again with magic following its public revelation in Far From Home, but this breaks open the multiverse, allowing supervillains from alternate realities who have fought versions of Parker to enter his universe.', 1.99, 7.99),
('Taxi Driver', 'Martin Scorsese', 'Taxi Driver is a 1976 American film directed by Martin Scorsese, written by Paul Schrader, and starring Robert De Niro, Jodie Foster, Cybill Shepherd, Harvey Keitel, Peter Boyle, Leonard Harris, and Albert Brooks. Set in a decaying and morally bankrupt New York City following the Vietnam War, the film follows Travis Bickle (De Niro), a taxi driver and veteran, and his deteriorating mental state as he works nights in the city.', 0.99, 5.99),
('Schindlers List', 'Steven Spilberg', 'Schindlers List is a 1993 American epic historical drama film directed and produced by Steven Spielberg and written by Steven Zaillian. It is based on the 1982 non-fiction novel Schindlers Ark by Australian novelist Thomas Keneally. The film follows Oskar Schindler, a German industrialist who saved more than a thousand mostly Polish-Jewish refugees from the Holocaust by employing them in his factories during World War II. It stars Liam Neeson as Schindler, Ralph Fiennes as SS officer Amon Göth and Ben Kingsley as Schindlers Jewish accountant Itzhak Stern.', 0.99, 5.99),
('The Martian', 'Ridley Scott', 'The Martian is a 2015 science fiction film directed by Ridley Scott and starring Matt Damon. Drew Goddard adapted the screenplay from the 2011 novel The Martian by Andy Weir. The film depicts an astronauts lone struggle to survive on Mars after being left behind, and the efforts of NASA to rescue him and bring him home to Earth. It also stars Jessica Chastain, Jeff Daniels, Kristen Wiig, Chiwetel Ejiofor, Sean Bean, Michael Peña, Kate Mara, Sebastian Stan, Aksel Hennie, Mackenzie Davis, Donald Glover, and Benedict Wong.', 0.99, 6.99),
('A Better Tomorrow', 'John Woo', 'A Better Tomorrow is a 1986 Hong Kong action film directed by John Woo and starring Ti Lung, Leslie Cheung and Chow Yun-fat. The film had a profound influence on Hong Kong action cinema, and has been recognised as a landmark film credited with setting the template for the heroic bloodshed genre, with considerable influence on both the Hong Kong film industry and Hollywood.', 0.79, 3.99),
('Inception', 'Christopher Nolan', 'Inception is a 2010 science fiction action film[4][5][6] written and directed by Christopher Nolan, who also produced the film with Emma Thomas, his wife. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another persons idea into a targets subconscious. The ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page,[a] Tom Hardy, Dileep Rao, Cillian Murphy, Tom Berenger, and Michael Caine.', 0.99, 4.99),
('Edward Scissorhands', 'Tim Burton', 'Edward Scissorhands is a 1990 American fantasy romance film[4] directed by Tim Burton. It was produced by Burton and Denise Di Novi, and written by Caroline Thompson from a story by her and Burton. Johnny Depp plays an artificial humanoid named Edward, an unfinished creation who has scissor blades instead of hands. The young man is taken in by a suburban family and falls in love with their teenage daughter, Kim (Winona Ryder). Additional roles were played by Dianne Wiest, Anthony Michael Hall, Kathy Baker, Vincent Price, and Alan Arkin.', 0.80, 4.99),
('Spirited Away', 'Hayao Miyazaki', 'Spirited Away (Japanese: 千と千尋の神隠し, Hepburn: Sen to Chihiro no Kamikakushi, Sen and Chihiros Spiriting Away) is a 2001 Japanese animated fantasy film written and directed by Hayao Miyazaki, animated by Studio Ghibli for Tokuma Shoten, Nippon Television Network, Dentsu, Buena Vista Home Entertainment, Tohokushinsha Film, and Mitsubishi.[7] The film features the voices of Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takeshi Naito, Yasuko Sawaguchi, Tsunehiko Kamijō, Takehiko Ono, and Bunta Sugawara. Spirited Away tells the story of Chihiro Ogino (Hiiragi), a ten-year-old girl who, while moving to a new neighborhood, enters the world of Kami (spirits of Japanese Shinto folklore).[8] After her parents are turned into pigs by the witch Yubaba (Natsuki), Chihiro takes a job working in Yubabas bathhouse to find a way to free herself and her parents and return to the human world.', 0.49, 2.99),
('Sherlock Holmes', 'Guy Ritchie', 'Sherlock Holmes is a 2009 period mystery action film based on the character of the same name created by Sir Arthur Conan Doyle. The film was directed by Guy Ritchie and produced by Joel Silver, Lionel Wigram, Susan Downey, and Dan Lin. The screenplay, by Michael Robert Johnson, Anthony Peckham, and Simon Kinberg, was developed from a story by Wigram and Johnson. Robert Downey Jr. and Jude Law portray Sherlock Holmes and Dr. John Watson, respectively. In 1890, eccentric detective Holmes and his companion Watson are hired by a secret society to foil a mysticists plot to gain control of Britain by seemingly supernatural means. Rachel McAdams stars as their former adversary Irene Adler and Mark Strong portrays villain Lord Henry Blackwood.', 0.99, 5.99),
('Reservoir Dogs', 'Quentin Tarantino', 'Reservoir Dogs is a 1992 American crime film written and directed by Quentin Tarantino in his feature-length debut. It stars Harvey Keitel, Tim Roth, Chris Penn, Steve Buscemi, Lawrence Tierney, Michael Madsen, Tarantino, and Edward Bunker as diamond thieves whose planned heist of a jewelry store goes terribly wrong. The film depicts the events before and after, but not during, the heist. Kirk Baltz, Randy Brooks, and Steven Wright also play supporting roles. It incorporates many motifs that have become Tarantinos hallmarks: violent crime, pop culture references, profanity, and nonlinear storytelling.', 0.99, 4.99),
('Avatar', 'James Cameron', 'Avatar (marketed as James Camerons Avatar) is a 2009 American epic science fiction film directed, written, produced, and co-edited by James Cameron and starring Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez, and Sigourney Weaver. The film is set in the mid-22nd century when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the valuable mineral unobtanium.[9][10][11] The expansion of the mining colony threatens the continued existence of a local tribe of Navi – a humanoid species indigenous to Pandora. The films title refers to a genetically engineered Navi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora.', 1.49, 6.99),
('Million Dollar Baby', 'Clint Eastwood', 'Million Dollar Baby is a 2004 American sports drama film directed, co-produced, scored by and starring Clint Eastwood from a screenplay written by Paul Haggis, based on short stories by F.X. Toole, the pen name of fight manager and cutman Jerry Boyd. It also stars Hilary Swank, and Morgan Freeman. The film follows Margaret "Maggie" Fitzgerald (Swank), an underdog amateur boxer who is helped by an underappreciated boxing trainer (Eastwood) to achieve her dream of becoming a professional.', 0.99, 4.99),
('Apocalypse Now', 'Francis Coppola', 'Apocalypse Now is a 1979 American epic psychological[6] war film directed and produced by Francis Ford Coppola. It stars Marlon Brando, Robert Duvall, Martin Sheen, Frederic Forrest, Albert Hall, Sam Bottoms, Laurence Fishburne, and Dennis Hopper. The screenplay, co-written by Coppola and John Milius with narration written by Michael Herr, is loosely based on the 1899 novella Heart of Darkness by Joseph Conrad, with the setting changed from late 19th-century Congo to the Vietnam War. The film follows a river journey from South Vietnam into Cambodia undertaken by Captain Benjamin L. Willard (Sheen), who is on a secret mission to assassinate Colonel Kurtz (Brando), a renegade Army Special Forces officer accused of murder and who is presumed insane.', 0.99, 5.99)


select * from userApp
select * from movieApp